language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - android-21
    - sys-img-armeabi-v7a-android-wear-21
