language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - build-tools-23.0.0
    - android-23
    - sys-img-armeabi-v7a-android-wear-23
